Repository Yoast/YoastSEO.js, pull requests merged in 2018-05, with the labels that each got.

#1482 Skip articles in KeywordTitle assessment
  spec/SEOAssessorSpec.js
  spec/assessments/titleKeywordSpec.js
  spec/cornerstone/SEOAssessorSpec.js
  spec/researches/findKeywordInPageTitleSpec.js
  spec/researches/findKeywordInPageitleSpec.js
  spec/stringProcessing/addWordBoundarySpec.js
  spec/stringProcessing/createWordRegexSpec.js
  src/assessments/seo/keyphraseLengthAssessment.js
  src/assessments/seo/titleKeywordAssessment.js
  src/cornerstone/seoAssessor.js
  src/researches/dutch/functionWords.js
  src/researches/english/functionWords.js
  src/researches/findKeywordInPageTitle.js
  src/researches/french/functionWords.js
  src/researches/german/functionWords.js
  src/researches/italian/functionWords.js
  src/researches/portuguese/functionWords.js
  src/researches/spanish/functionWords.js
  src/seoAssessor.js
  src/stringProcessing/addWordboundary.js
Labels: enhancement, text analysis

#1495 Make SnippetPreview optional
  src/app.js
Labels: code-review ★

#1487 Add Catalan transition words
  spec/helpers/getTransitionWordsSpec.js
  spec/researches/findTransitionWordsSpec.js
  src/assessments/readability/transitionWordsAssessment.js
  src/helpers/getTransitionWords.js
  src/researches/catalan/transitionWords.js
  src/researches/catalan/twoPartTransitionWords.js
Labels: development

#1506 Add flesch reading ease assessment for French
  spec/assessments/passiveVoiceAssessmentSpec.js
  spec/assessments/sentenceLengthInTextSpec.js
  spec/researches/calculateFleschReadingSpec.js
  spec/stringProcessing/syllables/countFrenchSpec.js
  src/assessments/readability/fleschReadingEaseAssessment.js
  src/config/syllables.js
  src/config/syllables/fr.json
  src/researches/calculateFleschReading.js
Labels: needs-code-review lingo, text analysis
