Repository Yoast/YoastSEO.js, pull requests merged in 2018-06, with the labels that each got.

#1520 Update language table
  README.md
Labels: needs-code-review lingo

#1529 Add Polish transition words
  spec/helpers/getTransitionWordsSpec.js
  spec/researches/findTransitionWordsSpec.js
  src/assessments/readability/transitionWordsAssessment.js
  src/helpers/getTransitionWords.js
  src/researches/polish/transitionWords.js
  src/researches/polish/twoPartTransitionWords.js
Labels: enhancement, needs-code-review lingo

#1523 Filter prominent word combinations ending with 's
  spec/stringProcessing/relevantWordsSpec.js
  src/stringProcessing/relevantWords.js
Labels: development lingo

#1537 Use normalized quotes for most keyword assessments
  spec/researches/findKeywordInPageitleSpec.js
  spec/stringProcessing/matchTextWithWordSpec.js
  src/researches/findKeywordInFirstParagraph.js
  src/researches/findKeywordInPageTitle.js
  src/researches/keywordCount.js
  src/stringProcessing/matchTextWithWord.js
  src/stringProcessing/subheadingsMatch.js
Labels: development lingo

#1539 Add Polish prominent words
  spec/stringProcessing/relevantWordsPolishSpec.js
  src/helpers/getFunctionWords.js
  src/researches/polish/functionWords.js
Labels: enhancement, needs-code-review lingo, text analysis

#1527 Improve image assessment by checking how often the keyword is included in alt-tags
  spec/assessments/textImagesSpec.js
  src/assessments/seo/textImagesAssessment.js
Labels: content analysis 2.0, development lingo

#1559 Add French and Spanish Flesch Reading Ease Assessment
  README.md
  spec/assessments/passiveVoiceAssessmentSpec.js
  spec/assessments/sentenceLengthInTextSpec.js
  spec/researches/calculateFleschReadingSpec.js
  spec/stringProcessing/syllables/countFrenchSpec.js
  spec/stringProcessing/syllables/countSpanishSpec.js
  src/assessments/readability/fleschReadingEaseAssessment.js
  src/config/syllables.js
  src/config/syllables/es.json
  src/config/syllables/fr.json
  src/researches/calculateFleschReading.js
Labels: code-review lingo

#1540 Add passive voice assessment for Italian
  README.md
  spec/researches/getPassiveVoiceItalianSpec.js
  spec/researches/italian/passiveVoice/ItalianParticipleSpec.js
  spec/researches/italian/passiveVoice/ItalianSentencePartSpec.js
  spec/researches/passiveVoice/getParticiplesItalianSpec.js
  spec/researches/passiveVoice/getSentencePartsItalianSpec.js
  spec/researches/passiveVoice/matchParticiplesItalianSpec.js
  src/assessments/readability/passiveVoiceAssessment.js
  src/researches/italian/functionWords.js
  src/researches/italian/passiveVoice/ItalianParticiple.js
  src/researches/italian/passiveVoice/SentencePart.js
  src/researches/italian/passiveVoice/auxiliaries.js
  src/researches/italian/passiveVoice/participles.js
  src/researches/italian/passiveVoice/stopwords.js
  src/researches/passiveVoice/periphrastic/getParticiples.js
  src/researches/passiveVoice/periphrastic/getSentenceParts.js
  src/researches/passiveVoice/periphrastic/matchParticiples.js
  src/stringProcessing/directPrecedenceException.js
  src/stringProcessing/precedenceException.js
Labels: needs-code-review lingo
