Repository Yoast/YoastSEO.js, pull requests merged in 2018-12, with the labels that each got.

#2033 Fix checking for window when loading module
  src/worker/createWorker.js
Labels: acceptance lingo

#2046 Update changelog for 9.3
  CHANGELOG.md
Labels: acceptance lingo

#2053 Update changelog for 9.4
  CHANGELOG.md
Labels: acceptance lingo

#2060 Release yoast seo/9.4
  CHANGELOG.md
Labels: needs-code-review lingo

#2056 Add Node inheritance to StructuredNode
  spec/tree/values/nodes/StructuredNodeSpec.js
  spec/tree/values/nodes/StructuredTextSpec.js
  src/tree/values/nodes/StructuredNode.js
Labels: needs-code-review lingo

#2074 Disable Swedish readability analysis
  README.md
  spec/assessments/sentenceBeginningsSpec.js
  spec/fullTextTests/testTexts/index.js
  spec/helpers/getFunctionWordsLanguagesSpec.js
  spec/stringProcessing/relevantWordsSwedishSpec.js
  src/assessments/readability/passiveVoiceAssessment.js
  src/assessments/readability/sentenceBeginningsAssessment.js
  src/assessments/readability/transitionWordsAssessment.js
  src/helpers/getFunctionWords.js
Labels: development lingo

#2077 Update changelog
  CHANGELOG.md
Labels: needs-acceptance lingo

#2076 Restore Swedish readability analysis
  README.md
  spec/assessments/sentenceBeginningsSpec.js
  spec/fullTextTests/testTexts/index.js
  spec/helpers/getFunctionWordsLanguagesSpec.js
  spec/stringProcessing/relevantWordsSwedishSpec.js
  src/assessments/readability/passiveVoiceAssessment.js
  src/assessments/readability/sentenceBeginningsAssessment.js
  src/assessments/readability/transitionWordsAssessment.js
  src/helpers/getFunctionWords.js
Labels: acceptance lingo

#2083 Remove JSDom from tests
  package.json
  spec/worker/AnalysisWebWorkerSpec.js
  spec/worker/scheduler/SchedulerSpec.js
  src/helpers/shortlinker/singleton.js
Labels: needs-code-review lingo
