Repository Yoast/YoastSEO.js, pull requests merged in 2018-07, with the labels that each got.

#1568 Add largest keyword distance assessment to assessor based on assessor options
  spec/SEOAssessorSpec.js
  spec/cornerstone/SEOAssessorSpec.js
  src/app.js
  src/cornerstone/seoAssessor.js
  src/seoAssessor.js
Labels: development lingo

#1564 Import premium data into paper
  src/app.js
Labels: development lingo

#1574 Add synonyms and keyword distribution assessment
  spec/SEOAssessorSpec.js
  spec/assessments/keywordDensitySpec.js
  spec/assessments/largestKeywordDistanceAssessmentSpec.js
  spec/assessments/topicDensitySpec.js
  spec/cornerstone/SEOAssessorSpec.js
  spec/markers/addMarkSingleWordSpec.js
  spec/markers/addMarkSpec.js
  spec/researches/getTopicDensitySpec.js
  spec/researches/keywordCountSpec.js
  spec/researches/largestKeywordDistanceSpec.js
  spec/researches/topicCountSpec.js
  spec/stringProcessing/indicesSpec.js
  spec/stringProcessing/matchTextWithWordSpec.js
  spec/stringProcessing/parseSynonymsSpec.js
  spec/stringProcessing/stripWordBoundariesSpec.js
  spec/values/paperSpec.js
  src/app.js
  src/assessments/seo/keywordDensityAssessment.js
  src/assessments/seo/largestKeywordDistanceAssessment.js
  src/assessments/seo/topicDensityAssessment.js
  src/cornerstone/seoAssessor.js
  src/markers/addMarkSingleWord.js
  src/researcher.js
  src/researches/findKeywordInFirstParagraph.js
  src/researches/findKeywordInPageTitle.js
  src/researches/getKeywordDensity.js
  src/researches/getTopicDensity.js
  src/researches/imageAltTags.js
  src/researches/keywordCount.js
  src/researches/keywordCountInUrl.js
  src/researches/largestKeywordDistance.js
  src/researches/metaDescriptionKeyword.js
  src/researches/topicCount.js
  src/seoAssessor.js
  src/stringProcessing/indices.js
  src/stringProcessing/matchTextWithArray.js
  src/stringProcessing/matchTextWithWord.js
  src/stringProcessing/parseSynonyms.js
  src/stringProcessing/removePunctuation.js
  src/stringProcessing/stripWordBoundaries.js
  src/stringProcessing/subheadingsMatch.js
  src/values/Paper.js
Labels: development lingo

#1580 Use keyword density instead of topic density when synonyms are set
  spec/assessments/keywordDensitySpec.js
  spec/assessments/largestKeywordDistanceAssessmentSpec.js
  spec/assessments/topicDensitySpec.js
  spec/researches/topicCountSpec.js
  src/assessments/seo/keywordDensityAssessment.js
  src/assessments/seo/largestKeywordDistanceAssessment.js
  src/assessments/seo/topicDensityAssessment.js
  src/cornerstone/seoAssessor.js
  src/researches/topicCount.js
  src/seoAssessor.js
Labels: development lingo

#1585 Change boundaries, add gray bullet, enable markings in good condition
  spec/assessments/largestKeywordDistanceAssessmentSpec.js
  src/assessments/seo/largestKeywordDistanceAssessment.js
Labels: development lingo

#1603 Change feedback strings
  spec/assessments/keywordDensitySpec.js
  src/assessments/seo/keywordDensityAssessment.js
Labels: code-review lingo

#1598 Expose more API to use
  index.js
  src/assessments/index.js
  src/bundledPlugins/index.js
  src/helpers/index.js
  src/markers/index.js
  src/stringProcessing/index.js
Labels: acceptance lingo

#1649 Add Polish to README table
  README.md
Labels: acceptance lingo
