Repository Yoast/YoastSEO.js, pull requests merged in 2018-08, with the labels that each got.

#1689 Add HTML parser
  src/worker/analysis.worker.js
Labels: development lingo

#1698 Update fontsize of snippet title measure element
  src/helpers/createMeasurementElement.js
Labels: code-review

#1704 Fix webpack example
  examples/webpack/src/App.js
  examples/webpack/src/analysis.worker.js
  examples/webpack/src/index.js
  src/worker/AnalysisWebWorker.js
Labels: needs-code-review lingo

#1718 Set the default queue system to FIFO
  src/worker/scheduler/Scheduler.js
Labels: needs-code-review lingo

#1731 Automatically parse and serialize all value objects send to and from the worker
  src/researches/sentences.js
  src/values/Mark.js
  src/values/Paper.js
  src/values/Participle.js
  src/values/Sentence.js
  src/values/SentencePart.js
  src/values/WordCombination.js
  src/worker/AnalysisWebWorker.js
  src/worker/AnalysisWorkerWrapper.js
  src/worker/transporter/index.js
  src/worker/transporter/parse.js
  src/worker/transporter/serialize.js
Labels: needs-code-review lingo

#1747 Upgrade most of our dependencies
  package.json
  yarn.lock
Labels: code-review lingo
