Repository Yoast/YoastSEO.js, pull requests merged in 2018-11, with the labels that each got.

#1905 Add Swedish prominent words
  spec/stringProcessing/relevantWordsSwedishSpec.js
  src/helpers/getFunctionWords.js
  src/researches/swedish/functionWords.js
Labels: enhancement, needs-code-review lingo, text analysis

#1975 Fix register modification docblocks
  src/app.js
Labels: acceptance lingo

#1953 Examples webpack work
  examples/webpack/.eslintrc
  examples/webpack/config/paths.js
  examples/webpack/config/webpack.config.dev.js
  examples/webpack/package.json
  examples/webpack/public/index.html
  examples/webpack/src/App.js
  examples/webpack/src/analysis.worker.js
  examples/webpack/src/components/Collapsible.js
  examples/webpack/src/components/Columns.js
  examples/webpack/src/components/Container.js
  examples/webpack/src/components/Controls.js
  examples/webpack/src/components/Input.js
  examples/webpack/src/components/Inputs.js
  examples/webpack/src/components/Markings.js
  examples/webpack/src/components/Results.js
  examples/webpack/src/components/ScoreIcon.js
  examples/webpack/src/components/SelectTestPaper.js
  examples/webpack/src/components/TextArea.js
  examples/webpack/src/components/WorkerStatus.js
  examples/webpack/src/components/headings.js
  examples/webpack/src/index.css
  examples/webpack/src/index.js
  examples/webpack/src/redux/utils/StoreSubscriber.js
  examples/webpack/src/utils/formatAnalyzeResult.js
  examples/webpack/yarn.lock
Labels: needs-code-review lingo

#1981 Remove unneeded functionWords argument from getRelevance call
  src/stringProcessing/relevantWords.js
Labels: code-review lingo

#1986 Add browsers, editor and recalibration to issue template
  .github/ISSUE_TEMPLATE.md
Labels: needs-acceptance lingo

#1987 Update issue template
  .github/ISSUE_TEMPLATE.md
Labels: code-review lingo

#2003 Feature/svenska
  README.md
  examples/webpack/config/webpack.config.dev.js
  examples/webpack/package.json
  examples/webpack/yarn.lock
  package.json
  spec/assessments/sentenceBeginningsSpec.js
  spec/fullTextTests/runFullTextTests.js
  spec/fullTextTests/testTexts/en/englishPaper1.html
  spec/fullTextTests/testTexts/en/englishPaper1.js
  spec/fullTextTests/testTexts/en/englishPaper2.html
  spec/fullTextTests/testTexts/en/englishPaper2.js
  spec/fullTextTests/testTexts/en/englishPaper3.html
  spec/fullTextTests/testTexts/en/englishPaper3.js
  spec/fullTextTests/testTexts/en/englishPaper4.html
  spec/fullTextTests/testTexts/en/englishPaper4.js
  spec/fullTextTests/testTexts/englishPaper1.js
  spec/fullTextTests/testTexts/englishPaper2.js
  spec/fullTextTests/testTexts/englishPaper3.js
  spec/fullTextTests/testTexts/englishPaper4.js
  spec/fullTextTests/testTexts/index.js
  spec/fullTextTests/testTexts/sv/swedishPaper1.html
  spec/fullTextTests/testTexts/sv/swedishPaper1.js
  spec/fullTextTests/testTexts/sv/swedishPaper2.html
  spec/fullTextTests/testTexts/sv/swedishPaper2.js
  spec/helpers/getFirstWordExceptionsSpec.js
  spec/helpers/getFunctionWordsLanguagesSpec.js
  spec/helpers/getTransitionWordsSpec.js
  spec/researches/findTransitionWordsSpec.js
  spec/researches/getPassiveVoiceSwedishSpec.js
  spec/researches/getSentenceBeginningsSpec.js
  spec/specHelpers/rawLoader.js
  spec/stringProcessing/relevantWordsSwedishSpec.js
  src/assessments/readability/passiveVoiceAssessment.js
  src/assessments/readability/sentenceBeginningsAssessment.js
  src/assessments/readability/transitionWordsAssessment.js
  src/helpers/getFirstWordExceptions.js
  src/helpers/getFunctionWords.js
  src/helpers/getTransitionWords.js
  src/researches/getPassiveVoice.js
  src/researches/getSentenceBeginnings.js
  src/researches/keywordCountInUrl.js
  src/researches/passiveVoice/morphological/determinePassiveSentence.js
  src/researches/swedish/firstWordExceptions.js
  src/researches/swedish/functionWords.js
  src/researches/swedish/passiveVoice/participles.js
  src/researches/swedish/transitionWords.js
  src/researches/swedish/twoPartTransitionWords.js
Labels: needs-code-review lingo

#2030 Improve YoastSEO.js README.md
  README.md
Labels: acceptance lingo
