Repository Yoast/YoastSEO.js, pull requests merged in 2018-10, with the labels that each got.

#1839 Update feedback strings in TitleKeyword assessment
  spec/assessments/TitleKeywordAssessmentSpec.js
  spec/fullTextTests/testTexts/englishPaper1.js
  spec/fullTextTests/testTexts/englishPaper2.js
  spec/fullTextTests/testTexts/englishPaper3.js
  src/assessments/seo/TitleKeywordAssessment.js
Labels: acceptance lingo

#1850 Update changelog
  CHANGELOG.md
Labels: code-review lingo

#1857 Fix missing word in sentence
  spec/assessments/TitleKeywordAssessmentSpec.js
  spec/fullTextTests/testTexts/englishPaper2.js
  src/assessments/seo/TitleKeywordAssessment.js
Labels: code-review lingo

#1879 Update changelog for 9.0 RC3
  CHANGELOG.md
Labels: code-review lingo

#1892 Update changelog
  CHANGELOG.md
Labels: needs-code-review lingo

#1895 Update changelog
  CHANGELOG.md
Labels: development lingo

#1899 Fix errors
  spec/specHelpers/factory.js
  src/assessments/seo/MetaDescriptionKeywordAssessment.js
  src/assessments/seo/TitleKeywordAssessment.js
  src/helpers/includesAny.js
  src/researches/keyphraseDistribution.js
  src/researches/metaDescriptionKeyword.js
Labels: code-review lingo

#1923 Fix reference to empty self
  src/helpers/shortlinker/singleton.js
Labels: code-review lingo

#1919 Refactor seo assessments filenames and exports
  spec/assessments/metaDescriptionLengthSpec.js
  spec/assessments/outboundLinksSpec.js
  spec/assessments/pageTitleWidthSpec.js
  spec/assessments/subheadingsKeywordSpec.js
  spec/assessments/textImagesSpec.js
  spec/assessments/textLengthSpec.js
  spec/assessments/urlLengthSpec.js
  spec/fullTextTests/runFullTextTests.js
  src/assessments/index.js
  src/assessments/seo/MetaDescriptionLengthAssessment.js
  src/assessments/seo/OutboundLinksAssessment.js
  src/assessments/seo/PageTitleWidthAssessment.js
  src/assessments/seo/SubHeadingsKeywordAssessment.js
  src/assessments/seo/TextImagesAssessment.js
  src/assessments/seo/TextLengthAssessment.js
  src/assessments/seo/UrlLengthAssessment.js
  src/cornerstone/relatedKeywordAssessor.js
  src/cornerstone/seoAssessor.js
  src/relatedKeywordAssessor.js
  src/seoAssessor.js
  src/taxonomyAssessor.js
Labels: community-patch
