Repository Yoast/YoastSEO.js, pull requests merged in 2019-01, with the labels that each got.

#2079 Export SeoAssessor from project index
  index.js
Labels: community-patch, needs-acceptance lingo

#2089 Update changelog 9.4
  CHANGELOG.md
Labels: acceptance lingo

#2090 Add changelog items for release 1.47
  CHANGELOG.md
Labels: needs-code-review lingo

#2084 Fix some eslint warnings in YoastSEO.js
  Gruntfile.js
  grunt/config/eslint.js
  spec/assessments/fleschReadingEaseSpec.js
  spec/assessments/paragraphTooLongSpec.js
  spec/assessments/passiveVoiceAssessmentSpec.js
  spec/assessments/sentenceBeginningsSpec.js
  spec/assessments/sentenceLengthInDescriptionSpec.js
  spec/assessments/sentenceLengthInTextSpec.js
  spec/assessments/transitionWordsSpec.js
  spec/assessorSpec.js
  spec/contentAssessorSpec.js
  spec/cornerstone/contentAssessorSpec.js
  spec/helpers/typesSpec.js
  spec/pluggableSpec.js
  spec/researches/countSentencesFromTextSpec.js
  spec/snippetPreviewSpec.js
  spec/specHelpers/factory.js
  spec/values/assessmentResultSpec.js
  src/assessments/readability/fleschReadingEaseAssessment.js
  src/assessments/readability/paragraphTooLongAssessment.js
  src/assessments/readability/passiveVoiceAssessment.js
  src/assessments/readability/sentenceBeginningsAssessment.js
  src/assessments/readability/sentenceLengthInDescriptionAssessment.js
  src/assessments/readability/transitionWordsAssessment.js
  src/assessments/readability/wordComplexityAssessment.js
  src/assessments/seo/keywordStopWordsAssessment.js
  src/assessments/seo/urlStopWordsAssessment.js
  src/bundledPlugins/previouslyUsedKeywords.js
  src/researcher.js
  src/researches/german/passiveVoice/determinePassives.js
  src/researches/keywordCount.js
  src/researches/passiveVoice/periphrastic/getSentenceParts.js
  src/researches/passiveVoice/periphrastic/getSentencePartsSplitOnStopwords.js
  src/snippetPreview.js
  src/stringProcessing/markWordsInSentences.js
  src/stringProcessing/matchTextWithTransliteration.js
  src/stringProcessing/relevantWords.js
  src/stringProcessing/specialCharacterMappings.js
Labels: development lingo, owner: development

#2101 Upgrade webpack-dev-server by re-ejecting a create-react-app
  examples/webpack/README.md
  examples/webpack/config/env.js
  examples/webpack/config/jest/cssTransform.js
  examples/webpack/config/jest/fileTransform.js
  examples/webpack/config/paths.js
  examples/webpack/config/polyfills.js
  examples/webpack/config/webpack.config.dev.js
  examples/webpack/config/webpack.config.js
  examples/webpack/config/webpack.config.prod.js
  examples/webpack/config/webpackDevServer.config.js
  examples/webpack/package.json
  examples/webpack/public/index.html
  examples/webpack/public/manifest.json
  examples/webpack/scripts/build.js
  examples/webpack/scripts/start.js
  examples/webpack/scripts/test.js
  examples/webpack/yarn.lock
Labels: acceptance lingo

#2111 Use pull request branch when checking out the premium config on Travis
  grunt/config/shell.js
Labels: development lingo
